### ISSUE TITLE
Invalid request, an initial state could not be found

### ISSUE THREAD

**Issue by grahambryan** [sandrinodimattia/nextjs-auth0-example#8]
Great example, it has been very helpful! I have got it to work locally on my machine but I am having trouble getting it to work in a production environment (I am not using now). 

I launch my application with this `HOST=0.0.0.0 PORT=80 npm run start` that uses the script `next start -p $PORT --hostname $HOST`. I am able to login but when it redirects me using my api/callback I get this error `Invalid request, an initial state could not be found`, but only in production. Does anyone have any suggestions?

using next 9.1.5 and node 12.12.0

The auth0 setup is

Regular Web Application
Added Allowed callbacks: http://mydomain.com/api/callbacks
Added Allowed logouts:  http://mydomain.com/
OAuth using RS256, OIDC Conformant is True 

The error: 
```bash
Error: Invalid request, an initial state could not be found
    at Object.<anonymous> (node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:18:19)
    at Generator.next (<anonymous>)
    at node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (node_modules/tslib/tslib.js:106:16)
    at Object.handleCallback (node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:6:43)
    at callback (.next/server/static/BfCtWDV94nuOqqQfHvyvp/pages/api/callback.js:146:70)
    at Object.apiResolver (node_modules/next/dist/next-server/server/api-utils.js:39:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.handleApiRequest (node_modules/next/dist/next-server/server/next-server.js:367:9)
```

The error derives from here, 

```
        // Require that we have a state.
        const state = cookies['a0:state'];
        if (!state) {
            throw new Error('Invalid request, an initial state could not be found');
        }
```

Any reason why I may not be receiving the a0:state cookie?

**Comment by grahambryan** [comment]
moved to https://github.com/auth0/nextjs-auth0/issues/54
